using Xunit;

namespace CompanyEmployeeProject.EntityFrameworkCore;

[CollectionDefinition(CompanyEmployeeProjectTestConsts.CollectionDefinitionName)]
public class CompanyEmployeeProjectEntityFrameworkCoreCollection : ICollectionFixture<CompanyEmployeeProjectEntityFrameworkCoreFixture>
{

}
