using CompanyEmployeeProject.EntityFrameworkCore;
using Xunit;

namespace CompanyEmployeeProject.EntityFrameworkCore;

public class CompanyEmployeeProjectEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<CompanyEmployeeProjectEntityFrameworkCoreFixture>
{

}
